Add some pinned deps to runtime envs
drivendataorg/meta-vsc-descriptor-runtime pull request #34
Opened 2023-01-06 20:37 UTC by nateraw

Here I'm adding a few helpful deps for videos...

- `decord` a fast video decoder. probably very helpful for folks to make submissions faster.
- `pytorchvideo` - facebookresearch library containing a bunch of helpful video utilities
- `av` helpful reader/writer (used by pytorchvideo). Is a little slower than decord but has more features/I've found it to be a bit more stable in my experience

...as well as adding:
- `timm`, which has a bunch of pretrained vision models folks may want to leverage
- `transformers`, which has vision models as well (notably some nice video models I was playing with)

I also pinned the version of `pytorch-lightning` because lightning flash had a loose version of it in its requirements.

I didn't build this on CPU or GPU...I read there were GH actions so I'm hoping I can just work against that 😉 

Happy to discuss if you folks don't want some of these in the environment!

2023-01-06 21:09 UTC, chrisjkuch commented
Hey @nateraw - thanks for the PR! It looks like the build is failing because of a conflict:
```
The conflict is caused by:
    The user requested pytorchvideo==0.1.5
    lightning-flash[image,video] 0.8.1 depends on pytorchvideo==0.1.2; extra == "video"
```
Have you tested the build locally?

P.S. We are still undergoing internal discussions about your forum question, hoping to have more for you sooner rather than later.

2023-01-06 21:21 UTC, chrisjkuch commented
@nateraw Another failure:
```
The conflict is caused by:
    The user requested timm==0.6.12
    lightning-flash[image,video] 0.8.1 depends on timm>=0.4.5; extra == "image"
    segmentation-models-pytorch 0.3.1 depends on timm==0.4.12
    The user requested timm==0.6.12
    lightning-flash[image,video] 0.8.1 depends on timm>=0.4.5; extra == "image"
    segmentation-models-pytorch 0.3.0 depends on timm==0.4.12
    The user requested timm==0.6.12
    lightning-flash[image,video] 0.8.1 depends on timm>=0.4.5; extra == "image"
    segmentation-models-pytorch 0.2.1 depends on timm==0.4.12
    The user requested timm==0.6.12
    lightning-flash[image,video] 0.8.1 depends on timm>=0.4.5; extra == "image"
    segmentation-models-pytorch 0.2.0 depends on timm==0.4.12
```
Would you mind debugging this locally? It will probably be much, much faster to just create a fresh conda environment and attempt to install it locally, since you benefit from package caching that doesn't happen here.

2023-01-06 21:37 UTC, nateraw commented
ah darn. will take a look. Flash has a bit of a messy nest of deps, so will have to see if we can work around it. Folks are using that dep actively?

2023-01-06 21:46 UTC, chrisjkuch commented
TBH I'm not sure - I don't think any of the submission so far have included code execution components.

2023-01-06 21:53 UTC, nateraw commented
Can we remove flash in this PR then for now and cross the bridge if needed later? 🤞 

Just ran some tests...all in new conda envs. flash installs 57 deps with those extras. 25 deps with the vanilla install. Compared to others (transforms: 11, pytorchvideo: 11, timm: 10, ...) that's a LOT imo for something we dunno if we need

2023-01-06 21:53 UTC, chrisjkuch commented
FWIW I pinned `timm==0.4.12` and built a new env locally and it seemed to work - does that version suffice for your needs?

2023-01-06 21:55 UTC, nateraw commented
I think there are some newer models (+ accompanying pretrained weights) in `timm` that folks would want to maybe leverage, which is why I opted for newer version.

but it doesn't effect me right now so if ya want to do that, that's cool too

2023-01-06 21:55 UTC, nateraw commented
but you will run into this problem again! haha

2023-01-06 21:56 UTC, chrisjkuch commented
> Can we remove flash in this PR then for now and cross the bridge if needed later?

Let me give this some thought / discussion and get back to you

2023-01-06 21:57 UTC, nateraw commented
All good! Also FWIW the lightning team moves quick so maybe someone from their side can remedy this for us (pinging @borda)

2023-01-06 22:18 UTC, chrisjkuch commented
Another avenue - looks like the offending flash dependency [segmentation_models.pytorch](https://github.com/qubvel/segmentation_models.pytorch) just recently upgraded `timm` to 0.6.12 but has yet to cut a new release

2023-01-06 22:27 UTC, nateraw commented
maybe @qubvel can make a release? 👀 would be much appreciated :)

2023-01-06 23:00 UTC, chrisjkuch commented
> maybe qubvel can make a release? 👀 would be much appreciated :)

Looks like we'll get one shortly, let's try building again once it comes in.

2023-01-07 09:43 UTC, Borda commented
fyi, some compatibility is rolling over here: https://github.com/Lightning-AI/lightning-flash/pull/1487

2023-01-09 19:00 UTC, chrisjkuch commented
Alright @nateraw, pinning  `segmentation-models-pytorch==0.3.2` seems to solve all the outstanding issues - can you make the change & I'll run the builds and we can merge?

2023-01-09 19:16 UTC, chrisjkuch requested changes

2023-01-09 19:16 UTC, chrisjkuch commented on runtime/environment-cpu.yml
> +    - pytorchvideo==0.1.2
```suggestion
    - pytorchvideo==0.1.2
    - segmentation-models-pytorch==0.3.2
```

2023-01-09 19:16 UTC, chrisjkuch commented on runtime/environment-gpu.yml
> +    - pytorchvideo==0.1.2
```suggestion
    - pytorchvideo==0.1.2
    - segmentation-models-pytorch==0.3.2
```

2023-01-13 16:19 UTC, nateraw commented
@chrisjkuch you know if we could use the latest pytorchvideo in this case then? Or would we still be constrained to 1.2.0?

Sorry for late reply btw - in France for hugging face offsite so low availability.

2023-01-13 16:25 UTC, chrisjkuch commented
Yes, I think we're still constrained to `pytorchvideo==1.2.0` because of the flash dependency. If 1.5.0 is absolutely necessary, we can consider removing flash, but if we can help it I'd rather not.

2023-01-13 22:35 UTC, nateraw commented
Got it. having a look now!

2023-01-17 17:35 UTC, chrisjkuch approved these changes
alright we're building and good to go

2023-01-17 17:45 UTC, merged

2023-01-17 19:18 UTC, nateraw commented
Thanks!!! Trained a model this past weekend - excited to submit :) haha hopefully > 0.0 score this time.